### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by Secant1998** [rosinality/style-based-gan-pytorch#96]
Thank you so much for the Pre-trained model, but i failed with TITAN xp on _**generate.py**_

The problem is:
RuntimeError: CUDA out of memory. Tried to allocate 960.00 MiB (GPU 0; 6.00 GiB total capacity; 3.56 GiB already allocated; 308.14 MiB free; 4.30 GiB reserved in total by PyTorch)

I saw that using **_with torch.no_grad():_** could be OK, but I don't know which line should I put it in. Looking forward to your reply!

**Comment by rosinality** [comment]
torch.no_grad is already applied in generate.py. I think you may need to consider to reduece the number of samples. (`--n_row`, `--n_col` options)

**Comment by Secant1998** [comment]
Thank you for your prompt reply., the problem has been solved!!

I have some other minor questions:
1. Is Sample.png a totally fake stylegan-randomly-generated picture?
2. (For further research) I want to add some particular "Latent-Codes"(512×1) into generate.py and use it for training ResNet. Is there any adjustment required? 
3. I only need the function of face generating, can I just delete the lines used for feature mixing?

I'm a complete newbie of python & deep learning, and your instructions are very important for me!
                                                                                                                                With appreciation.

**Comment by rosinality** [comment]
1. Yes!
2. I think you don't need particular adjustment. Anyway, do you have any adjustments in mind?
3.  Yes, It is just for make a showcase samples.

**Comment by Secant1998** [comment]
Sorry, where can I put my eigenvector into generate.py instead of a random one?
I tried some locations but failed.

**Comment by rosinality** [comment]
You can pass it to the generator: https://github.com/rosinality/style-based-gan-pytorch/blob/master/generate.py#L29

**Comment by Secant1998** [comment]
> You can pass it to the generator: https://github.com/rosinality/style-based-gan-pytorch/blob/master/generate.py#L29

That works. 
Thanks 👍
